spring.application.name=hazmat-storage
server.port=8080


# Datenbank H2 In Memory
spring.datasource.url=jbdc:h2:mem:hazmatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Zugriff auf Datenbank über Browser localhost
spring.h2.console.enabled=true

# Hibernate soll nur prüfen ob Tabellen existieren, erstellen über Flyway
spring.jpa.hibernate.ddl-auto=validate