graph TD
    Start([POST /api/content]) --> LadeDB(Storage aus Datenbank laden)

    LadeDB --> Existiert{Storage gefunden?}

    Existiert -- Nein --> Error404[Abbruch 404 Not Found]
    Existiert -- Ja --> CheckHazardClass{Erlaubt der Storage Type\ndie mitgelieferte HazardClass?}

    CheckHazardClass -- Nein --> Error400D[Abbruch: 400 Bad Request \nEXPLOSIVE or NULL = SHELVES \nFLAMMABLE = PRESSURE\nTOXIC = CRYOGENIC \nRADIOACTIVE = COMPOST]
    CheckHazardClass -- Ja --> CheckUnit{Einheit des Inhalts dieselbe wie Lager?}

    CheckUnit -- Nein --> Error400A[Abbruch: 400 Bad Request Storage und Content\nmüssen dieselbe Maßeinheit haben]

    CheckUnit -- Ja --> CheckCapacity{Reicht die Restkapazität im Storage?}

    CheckCapacity -- Nein --> Error400B[Abbruch: 400 Bad Request Storage hat \nnicht genug Kapazität für neuen Content]
    CheckCapacity -- Ja --> Save[(Content in Storage speichern)]

    Save --> Success([201 Created])